In [18]:
import yfinance as yf
import vectorbt as vbt
import pandas as pd
import numpy as np
import plotly.express as px
from datetime import datetime, timedelta

In [2]:
today = datetime.today()
i_date = "2018-01-01"
f_date = "2024-05-01"
oversold = 25
period = 2
timeframe = "1d"

In [3]:
tickers = [ 
    "PETR4.SA", "VALE3.SA", "ITUB4.SA", "BBDC4.SA", "MGLU3.SA", "ABEV3.SA", "BBAS3.SA", "B3SA3.SA",
    "JBSS3.SA", "USIM5.SA", "WEGE3.SA", "SANB11.SA", "SUZB3.SA", "BRKM5.SA", "ELET3.SA",
    "GGBR4.SA", "CEAB3.SA", "CSNA3.SA", "ITSA4.SA", "RDOR3.SA", "BEEF3.SA", "LREN3.SA",
    "MULT3.SA", "HAPV3.SA", "EQTL3.SA", "TAEE11.SA", "EGIE3.SA", "KLBN11.SA", "TIMS3.SA", "BRFS3.SA",
    "RAIL3.SA", "NTCO3.SA", "IGTI11.SA", "MRFG3.SA", "UGPA3.SA", "LIGT3.SA", "ARZZ3.SA", "CCRO3.SA",
    "FLRY3.SA", "LWSA3.SA", "CYRE3.SA", "SOJA3.SA", "ENEV3.SA", "CPFE3.SA", "ALPA4.SA", "AESB3.SA",
    "VIVA3.SA", "TOTS3.SA", "RADL3.SA", "RENT3.SA", "AALR3.SA", "IRBR3.SA", "GOLL4.SA",
    "EZTC3.SA", "COGN3.SA", "POSI3.SA", "QUAL3.SA", "TEND3.SA", "JHSF3.SA",
    "TUPY3.SA", "SAPR11.SA", "CMIG4.SA", "SIMH3.SA", "BRIT3.SA", "PETZ3.SA",
    "BMOB3.SA", "BPAN4.SA", "ENJU3.SA", "MOVI3.SA", "TGMA3.SA", "BBSE3.SA", "MRVE3.SA",
    "EMBR3.SA", "CSAN3.SA", "CIEL3.SA",
    "NEOE3.SA", "ARZZ3.SA", "CVCB3.SA", "SBSP3.SA", "POMO4.SA", "PRIO3.SA",
    "PSSA3.SA", "ECOR3.SA", "LOGG3.SA", "CXSE3.SA", "YDUQ3.SA", "PCAR3.SA", "AMER3.SA", 
    "HYPE3.SA", "GOAU4.SA", "ENGI11.SA", "CRFB3.SA", "BRAP4.SA", "BPAC11.SA", "AZUL4.SA"
]

# Download data using yfinance
data = yf.download(tickers, start=i_date, end=f_date, interval=timeframe)

[*********************100%%**********************]  94 of 94 completed

In [25]:
close = data["Adj Close"]

# Wilder method for RSI
def rsi_indicator(close, window=14):
    rsi = vbt.RSI.run(close, window=window).rsi.to_numpy()
    
    # return rsi.rsi

# rsi = rsi_indicator(data['Close'], period)

In [31]:
ind = vbt.IndicatorFactory(
  input_names=["close"],
  param_names=["window"],
  output_names=["rsi"]
).from_apply_func(
  rsi_indicator,
  window=14
)

res = ind.run(
  data["Close"],
  window=2
)
res.rsi

custom_window           2                                                  \
Ticker           AALR3.SA    ABEV3.SA    AESB3.SA    ALPA4.SA    AMER3.SA
Date
2018-01-02            NaN         NaN         NaN         NaN         NaN
2018-01-03            NaN         NaN         NaN         NaN         NaN
2018-01-04     100.000000   29.411633         NaN    0.000000   77.142905
2018-01-05      76.470621   40.000191         NaN   93.750443   58.695625
2018-01-08       0.000000   66.666137         NaN   46.153818    0.000000
...                   ...         ...         ...         ...         ...
2024-04-24      53.703700   66.666667   23.076697  100.000000   50.000000
2024-04-25      10.714201   90.000238   27.272570  100.000000  100.000000
2024-04-26     100.000000    0.000000    0.000000  100.000000  100.000000
2024-04-29     100.000000   89.999809  100.000000  100.000000   50.000000
2024-04-30      33.333687  100.000000   92.105336   53.731352   50.000000

custom_window                                                              \
Ticker           ARZZ3.SA    AZUL4.SA    B3SA3.SA    BBAS3.SA    BBDC4.SA
Date
2018-01-02            NaN         NaN         NaN         NaN         NaN
2018-01-03            NaN         NaN         NaN         NaN         NaN
2018-01-04     100.000000   65.384587  100.000000  100.000000  100.000000
2018-01-05      47.656248   85.000525  100.000000  100.000000  100.000000
2018-01-08       0.000000    0.000000  100.000000  100.000000   95.238323
...                   ...         ...         ...         ...         ...
2024-04-24       0.000000    0.000000    0.000000   67.741955  100.000000
2024-04-25       0.000000    0.000000    0.000000    0.000000    0.000000
2024-04-26      40.869421   59.782624   78.000069    0.000000   95.652084
2024-04-29      77.049160  100.000000   82.978749  100.000000  100.000000
2024-04-30      17.646531   48.148102    0.000000   56.666836   74.999901

custom_window  ...                                                             \
Ticker         ...    TGMA3.SA    TIMS3.SA   TOTS3.SA    TUPY3.SA    UGPA3.SA
Date           ...
2018-01-02     ...         NaN         NaN        NaN         NaN         NaN
2018-01-03     ...         NaN         NaN        NaN         NaN         NaN
2018-01-04     ...  100.000000   14.285909  77.108296  100.000000   53.939412
2018-01-05     ...  100.000000   64.705849  77.646912  100.000000  100.000000
2018-01-08     ...  100.000000   37.931125  97.058886    5.000119  100.000000
...            ...         ...         ...        ...         ...         ...
2024-04-24     ...    0.000000   39.285836   0.000000    8.000122    0.000000
2024-04-25     ...   72.000122  100.000000   0.000000    0.000000   62.499957
2024-04-26     ...  100.000000  100.000000  44.444366   25.806471  100.000000
2024-04-29     ...   57.971075  100.000000  48.000336  100.000000   76.000214
2024-04-30     ...    0.000000  100.000000   0.000000   14.634090    0.000000

custom_window
Ticker           USIM5.SA    VALE3.SA   VIVA3.SA    WEGE3.SA    YDUQ3.SA
Date
2018-01-02            NaN         NaN        NaN         NaN         NaN
2018-01-03            NaN         NaN        NaN         NaN         NaN
2018-01-04     100.000000   40.475931        NaN    0.000000   17.647983
2018-01-05      55.445531  100.000000        NaN   29.411250    0.000000
2018-01-08      19.642951  100.000000        NaN  100.000000   20.689542
...                   ...         ...        ...         ...         ...
2024-04-24       0.000000   58.646563  96.154467   46.153733  100.000000
2024-04-25       0.000000   36.792528  44.642748  100.000000  100.000000
2024-04-26       0.000000    0.000000  66.666598  100.000000  100.000000
2024-04-29       3.333408  100.000000  95.384521  100.000000   67.164239
2024-04-30       3.225876   73.362429   0.000000  100.000000    0.000000

[1570 rows x 94 columns]